# Generated by Django 3.1.1 on 2020-09-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200926_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='link',
            new_name='link_id',
        ),
    ]
