# Generated by Django 3.1.1 on 2020-10-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20201001_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='price_getter',
            field=models.CharField(default='', max_length=200),
        ),
    ]
