# Generated by Django 3.1.1 on 2020-10-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_website_price_getter'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='price_getter_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='website',
            name='price_getter',
            field=models.CharField(max_length=200),
        ),
    ]
