# Generated by Django 3.1.1 on 2020-10-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_auto_20201008_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='price_getter_type',
            field=models.CharField(max_length=50),
        ),
    ]
